services:
  - type: web
    name: disaster-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
      - key: FLASK_ENV
        value: production

